# Generated by Django 3.0.2 on 2020-01-10 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserServiceRequestInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_requests', models.IntegerField(default=0)),
                ('type', models.IntegerField(choices=[(0, 'nlp')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('type', 'user')},
            },
        ),
    ]
